#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly ROOT
SOURCE_IMAGE="${SOURCE_IMAGE:-vllm-node-tf5-minimax-m3-dspark-20260722}"
TARGET_TAG="${TARGET_TAG:-ghcr.io/mpfaffenberger/minimax-m3-nvfp4-dspark-vllm:b44311b6-20260722-arm64}"
GHCR_USER="${GHCR_USER:-mpfaffenberger}"

[[ -n "${GHCR_TOKEN:-}" ]] || {
    echo "GHCR_TOKEN with write:packages is required" >&2
    echo "Pass it through the environment; never place it on the command line." >&2
    exit 1
}

"${ROOT}/scripts/audit-container.sh" "${SOURCE_IMAGE}"
printf '%s' "${GHCR_TOKEN}" | docker login ghcr.io -u "${GHCR_USER}" --password-stdin
docker tag "${SOURCE_IMAGE}" "${TARGET_TAG}"
docker push "${TARGET_TAG}"

digest="$(
    docker buildx imagetools inspect "${TARGET_TAG}" --format '{{json .Manifest}}' |
        python3 -c 'import json,sys; print(json.load(sys.stdin)["digest"])'
)"
repository="${TARGET_TAG%:*}"
image_ref="${repository}@${digest}"
cat > "${ROOT}/container/image.env" <<EOF
# Generated by scripts/publish-container.sh after a successful registry push.
IMAGE_TAG=${TARGET_TAG}
IMAGE_DIGEST=${digest}
IMAGE_REF=${image_ref}
EOF

printf '\nPublished immutable image:\n%s\n' "${image_ref}"
printf 'Commit container/image.env, then make the GHCR package public.\n'
